<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\APIPlatform.Playground\APIPlatform.Playground.csproj" />
    <ProjectReference Include="..\..\src\APIPlatform.CrudEngine\APIPlatform.CrudEngine.csproj" />
    <ProjectReference Include="..\..\src\APIPlatform.Authorization\APIPlatform.Rbac\APIPlatform.Rbac.csproj" />
    <ProjectReference Include="..\..\src\APIPlatform.Database\APIPlatform.Data.csproj" />
    <ProjectReference Include="..\..\..\nucleus\shared\Nucleus.SharedSchema\Nucleus.SharedSchema.csproj" />
  </ItemGroup>
</Project>
