using APIPlatform.Data.Execution;
using APIPlatform.Data.Options;
using APIPlatform.Data.Transactions;
using APIPlatform.Database.Migration.Abstractions;

namespace APIPlatform.Playground.Rbac;

/// <summary>
/// Creates the durable schema behind SqlServerRoleStore, replacing APIPlatform.Rbac's default
/// InMemoryRoleStore (its own doc comment flags it "not durable, not distributed-safe,
/// process-lifetime only"). Lives in Playground (the application), not inside APIPlatform.Rbac or
/// APIPlatform.Database.Migration — Rbac never references APIPlatform.Data directly, so any real
/// schema for it is necessarily app-supplied, same reasoning as EmployeeSqlServerMigration.
/// Same no-IDENTITY/no-NEWID()/no-GETDATE() convention: every Id is supplied by the caller
/// (SqlServerRoleStore), never generated by SQL Server. SQL Server only, matching this host.
/// RbacRoles/RbacPermissionGrants/RbacPolicyRules are keyed by (TenantId, ...) — more strictly
/// tenant-scoped than InMemoryRoleStore's own Dictionary&lt;string, Role&gt; (keyed by Id alone),
/// which doesn't matter for this single-tenant host but is the more correct shape to persist.
/// </summary>
public sealed class RbacSqlServerMigration : IMigration
{
    public string MigrationId => "Rbac.Schema.v1";

    public int Version => 1;

    public string Description => "Creates the durable RBAC tables (Roles, UserRoles, PermissionGrants, PolicyRules).";

    public DatabaseProvider SupportedProvider => DatabaseProvider.SqlServer;

    private const string CreateRolesTableSql = @"
        CREATE TABLE [RbacRoles] (
            [TenantId]     NVARCHAR(100) NOT NULL,
            [Id]           NVARCHAR(100) NOT NULL,
            [Name]         NVARCHAR(200) NOT NULL,
            [ParentRoleId] NVARCHAR(100) NULL,
            [IsSystemRole] BIT           NOT NULL,
            CONSTRAINT [PK_RbacRoles] PRIMARY KEY ([TenantId], [Id])
        )";

    private const string CreateUserRolesTableSql = @"
        CREATE TABLE [RbacUserRoles] (
            [TenantId] NVARCHAR(100) NOT NULL,
            [UserId]   NVARCHAR(100) NOT NULL,
            [RoleId]   NVARCHAR(100) NOT NULL,
            CONSTRAINT [PK_RbacUserRoles] PRIMARY KEY ([TenantId], [UserId], [RoleId])
        )";

    private const string CreatePermissionGrantsTableSql = @"
        CREATE TABLE [RbacPermissionGrants] (
            [Id]            UNIQUEIDENTIFIER NOT NULL,
            [TenantId]      NVARCHAR(100)     NOT NULL,
            [RoleId]        NVARCHAR(100)     NULL,
            [UserId]        NVARCHAR(100)     NULL,
            [PermissionKey] NVARCHAR(200)     NOT NULL,
            [Effect]        NVARCHAR(10)      NOT NULL,
            CONSTRAINT [PK_RbacPermissionGrants] PRIMARY KEY ([Id])
        )";

    private const string CreatePolicyRulesTableSql = @"
        CREATE TABLE [RbacPolicyRules] (
            [Id]            UNIQUEIDENTIFIER NOT NULL,
            [TenantId]      NVARCHAR(100)     NOT NULL,
            [Name]          NVARCHAR(200)     NOT NULL,
            [PermissionKey] NVARCHAR(200)     NOT NULL,
            [ResourceType]  NVARCHAR(20)      NOT NULL,
            [Priority]      INT               NOT NULL,
            CONSTRAINT [PK_RbacPolicyRules] PRIMARY KEY ([Id])
        )";

    public async Task ApplyAsync(IDatabaseExecutor executor, IDatabaseTransaction? transaction, CancellationToken cancellationToken = default)
    {
        // One statement per ExecuteAsync call, same granularity EmployeeSqlServerMigration uses —
        // keeps each DDL statement its own round trip so a failure names the exact table at fault.
        await executor.ExecuteAsync(CreateRolesTableSql, transaction: transaction, cancellationToken: cancellationToken);
        await executor.ExecuteAsync(CreateUserRolesTableSql, transaction: transaction, cancellationToken: cancellationToken);
        await executor.ExecuteAsync(CreatePermissionGrantsTableSql, transaction: transaction, cancellationToken: cancellationToken);
        await executor.ExecuteAsync(CreatePolicyRulesTableSql, transaction: transaction, cancellationToken: cancellationToken);
    }
}
