<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\APIPlatform.Foundation\APIPlatform.Foundation.csproj" />
    <ProjectReference Include="..\APIPlatform.Data\APIPlatform.Data.csproj" />
    <ProjectReference Include="..\Nucleus.SharedSchema\Nucleus.SharedSchema.csproj" />
  </ItemGroup>
</Project>
