-- APIPlatform.Notification — SAP HANA reference schema.
-- IDs and timestamps are generated by the API, never the database: no SEQUENCE or
-- CURRENT_TIMESTAMP/CURRENT_UTCTIMESTAMP defaults. Apply by hand, or via
-- APIPlatform.Database.Migration's NotificationHanaMigration (see that package's README) — keep
-- both in sync: same table shape, keys, and indexes.
--
-- Column-type notes vs. the SQL Server schema (001_CreateNotificationTables.sql), which is the
-- source of truth for structure/indexes — only types differ, never shape:
--   NVARCHAR(MAX) -> NCLOB   (HANA has no MAX length; large opaque text uses NCLOB)
--   DATETIME2(3)  -> TIMESTAMP
--   BIT           -> BOOLEAN

CREATE COLUMN TABLE "Notifications"
(
    "Id"            NVARCHAR(36)  NOT NULL,
    "Application"   NVARCHAR(64)  NOT NULL,
    "EntityType"    NVARCHAR(128) NULL,
    "EntityId"      NVARCHAR(128) NULL,
    "EventType"     NVARCHAR(128) NOT NULL,
    "Title"         NVARCHAR(400) NOT NULL,
    "Message"       NCLOB         NULL,
    "Data"          NCLOB         NULL,
    "CreatedBy"     NVARCHAR(36)  NULL,
    "CreatedOnUtc"  TIMESTAMP     NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Notifications_Application_CreatedOnUtc" ON "Notifications" ("Application", "CreatedOnUtc" DESC);
CREATE INDEX "IX_Notifications_Entity" ON "Notifications" ("Application", "EntityType", "EntityId", "CreatedOnUtc" DESC);

CREATE COLUMN TABLE "NotificationTargets"
(
    "Id"             NVARCHAR(36)  NOT NULL,
    "NotificationId" NVARCHAR(36)  NOT NULL,
    "TargetKind"     TINYINT       NOT NULL, -- 0 = All, 1 = User, 2 = Group
    "TargetValue"    NVARCHAR(128) NULL,     -- user id or group code; NULL only when TargetKind = All
    "IsExclusion"    BOOLEAN       NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_NotificationTargets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NotificationTargets_Notifications" FOREIGN KEY ("NotificationId")
        REFERENCES "Notifications" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_NotificationTargets_Notification" ON "NotificationTargets" ("NotificationId", "IsExclusion", "TargetKind", "TargetValue");

CREATE COLUMN TABLE "NotificationUserStates"
(
    "UserId"          NVARCHAR(36) NOT NULL,
    "Application"     NVARCHAR(64) NOT NULL,
    "LastReadOnUtc"   TIMESTAMP    NULL,
    "LastSyncedOnUtc" TIMESTAMP    NULL,
    "UpdatedOnUtc"    TIMESTAMP    NOT NULL,
    CONSTRAINT "PK_NotificationUserStates" PRIMARY KEY ("UserId", "Application")
);
