-- APIPlatform.Notification — SQL Server reference schema.
-- IDs and timestamps are generated by the API, never the database: no IDENTITY, SEQUENCE,
-- NEWID(), or GETDATE()/DEFAULT time expressions. Apply via the consuming application's own
-- deployment process — the platform has no migration runner yet.

CREATE TABLE [Notifications]
(
    [Id]            NVARCHAR(36)   NOT NULL,
    [Application]   NVARCHAR(64)   NOT NULL,
    [EntityType]    NVARCHAR(128)  NULL,
    [EntityId]      NVARCHAR(128)  NULL,
    [EventType]     NVARCHAR(128)  NOT NULL,
    [Title]         NVARCHAR(400)  NOT NULL,
    [Message]       NVARCHAR(MAX)  NULL,
    [Data]          NVARCHAR(MAX)  NULL,
    [CreatedBy]     NVARCHAR(36)   NULL,
    [CreatedOnUtc]  DATETIME2(3)   NOT NULL,
    CONSTRAINT [PK_Notifications] PRIMARY KEY ([Id])
);

-- Anchors both the recipient-match and entity-history queries: filter by Application (and,
-- for entity history, EntityType/EntityId) before the per-notification EXISTS/NOT EXISTS
-- check against NotificationTargets.
CREATE INDEX [IX_Notifications_Application_CreatedOnUtc] ON [Notifications] ([Application], [CreatedOnUtc] DESC);
CREATE INDEX [IX_Notifications_Entity] ON [Notifications] ([Application], [EntityType], [EntityId], [CreatedOnUtc] DESC);

CREATE TABLE [NotificationTargets]
(
    [Id]             NVARCHAR(36)  NOT NULL,
    [NotificationId] NVARCHAR(36)  NOT NULL,
    [TargetKind]     TINYINT       NOT NULL, -- 0 = All, 1 = User, 2 = Group
    [TargetValue]    NVARCHAR(128) NULL,     -- user id or group code; NULL only when TargetKind = All
    [IsExclusion]    BIT           NOT NULL CONSTRAINT [DF_NotificationTargets_IsExclusion] DEFAULT (0),
    CONSTRAINT [PK_NotificationTargets] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_NotificationTargets_Notifications] FOREIGN KEY ([NotificationId])
        REFERENCES [Notifications] ([Id]) ON DELETE CASCADE
);

-- Supports NotificationSqlBuilder.RecipientMatch's EXISTS/NOT EXISTS pair directly: seek by
-- NotificationId, then by IsExclusion, then by TargetKind/TargetValue.
CREATE INDEX [IX_NotificationTargets_Notification] ON [NotificationTargets] ([NotificationId], [IsExclusion], [TargetKind], [TargetValue]);

CREATE TABLE [NotificationUserStates]
(
    [UserId]          NVARCHAR(36) NOT NULL,
    [Application]     NVARCHAR(64) NOT NULL,
    [LastReadOnUtc]   DATETIME2(3) NULL,  -- NULL = user has never marked anything read for this application
    [LastSyncedOnUtc] DATETIME2(3) NULL,  -- distinct from LastReadOnUtc — last client poll, not last acknowledgement
    [UpdatedOnUtc]    DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_NotificationUserStates] PRIMARY KEY ([UserId], [Application])
);
