using APIPlatform.Data.Execution;
using APIPlatform.Data.Options;
using APIPlatform.Data.Transactions;
using APIPlatform.Database.Migration.Abstractions;

namespace APIPlatform.Playground.Migrations;

/// <summary>
/// Creates the Employees table for the Phase 2 "one generic entity end-to-end" test. Uses the
/// platform's versioned migration engine (APIPlatform.Database.Migration/IMigration) — the
/// mechanism for schema that ships with a release and must be applied exactly once, as opposed to
/// ISchemaMigrationService, which builds tables from a request body at run time. It lives
/// inside Playground (the application/test host), not inside APIPlatform.Database.Migration
/// (a platform assembly), so the platform itself gains zero Employee-specific knowledge.
/// Follows the platform's documented convention exactly: no IDENTITY, no NEWID(), no
/// GETDATE()/column default — Id and timestamps are always supplied by the caller
/// (EmployeesController / IEntityDefaultValueProvider), never generated by SQL Server.
/// SQL Server only: this phase is explicitly scoped to SQL Server runtime validation.
/// </summary>
public sealed class EmployeeSqlServerMigration : IMigration
{
    public string MigrationId => "Employee.Schema.v1";

    public int Version => 1;

    public string Description => "Creates the Employees table (Phase 2 generic-entity validation).";

    public DatabaseProvider SupportedProvider => DatabaseProvider.SqlServer;

    private const string CreateTableSql = @"
        CREATE TABLE [Employees] (
            [Id]           UNIQUEIDENTIFIER NOT NULL,
            [EmployeeCode] NVARCHAR(20)      NOT NULL,
            [Name]         NVARCHAR(200)     NOT NULL,
            [Email]        NVARCHAR(256)     NOT NULL,
            [Department]   NVARCHAR(100)     NULL,
            [IsActive]     BIT               NOT NULL,
            [CreatedOn]    DATETIMEOFFSET    NOT NULL,
            [ModifiedOn]   DATETIMEOFFSET    NULL,
            CONSTRAINT [PK_Employees] PRIMARY KEY ([Id])
        )";

    public async Task ApplyAsync(IDatabaseExecutor executor, IDatabaseTransaction? transaction, CancellationToken cancellationToken = default)
    {
        await executor.ExecuteAsync(CreateTableSql, transaction: transaction, cancellationToken: cancellationToken);
    }
}
